language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install -r build-requirements.txt

script:
  - rr-paper  #test if the cmdline app runs at least
  - nosetests -sv --with-coverage --cover-package=rr rr #runs test
  - sphinx-build -b doctest doc sphinx
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - coveralls #uploads coverage report to coveralls.io
  - python setup.py sdist
  - twine check dist/*.tar.gz
  - rm -rf dist rr.egg-info

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: "$GITHUB_TOKEN"
    local_dir: "./sphinx/"
    on:
      branch: master
      condition: "$TRAVIS_PYTHON_VERSION = 3.8"
  - provider: pypi
    server: https://test.pypi.org/legacy/ # Remove to deployment on pypi.org
    username: "__token__"
    password:
      secure: stX4Gqh//s2Nvat57H6WUjOS1PP3CSxN2dX/7aRBcmFHwjkVKzATSESxvGq1B6iyBCG6TSoQNLWWztAfxPRJdATTA3EIoxSWeVZEIogRtDcEDiifFzT/WmGkGvyqgEijNGyA39xNhrnEmQyb30+WUu9XB9IB2WcuPzJVIH69Eh4KC1X76KS+nSasSuNn0apic/HjQkq+BUxk9DOrlpPEycMRk/DciREBRtF5PtPLHFl4rANAtDHVDSQ+uEgqgHzH4/0CpeOeGCyG3VQFkCCOeZEwAMNg/DjDZRS0epjYexdmjeNZp5zSV4mUPW2QEBGcgSpcJaZY+3lrwG1JeBOk5AYNtgGvXCwxh39rRU05mvzdNontf0s0rWpVeP1c5qALaLnLggtLkadTRf64KiUzw4l9Om3yeLMyA2OsLmU4OsLwTAAgYkBdTxlNmIh69S/Fr5wQID0XoqhZUyN4xbu4uMZZTq0uoVwggEo43fXxjoBVrafas1KlQfCNzjQx7pU2Z2uQf5T3Boi8EfPnPgivA8/GTGaEgmY//rqqxpXXQ0RjRiMwfvfgrCprlMvWTyNrfAmWWFRhlraKul0TjSK+PrSJVMar7m1s7pjyKOIFGj46vA5zn9d6LcM75OczP8awMMA2p1HDVmYs7aETR2MZ7Konk7p8TIjduYnBl+xrJVE=
    on:
      tags: true
      condition: "$TRAVIS_PYTHON_VERSION = 3.8"
