language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install -r build-requirements.txt

script:
  - rr-paper  #test if the cmdline app runs at least
  - nosetests -sv --with-coverage --cover-package=rr rr #runs test
  - sphinx-build -b doctest doc sphinx
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - coveralls #uploads coverage report to coveralls.io

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./sphinx/
    on:
        branch: master
        condition: $TRAVIS_PYTHON_VERSION = 3.8
